model:
  base_learning_rate: 4.5e-6
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512
        n_layer: 24
        n_head: 16
        n_embd: 1024
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2023-05-17T07-14-14_custom_vqgan/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0

        lossconfig:
          target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: False
            disc_in_channels: 3
            disc_start: 30001
            disc_weight: 0.8
            codebook_weight: 1.0
    cond_stage_config:
        target: taming.modules.transformer.mingpt
        params:
          embed_dim: 256
          n_embed: 1024
          ddconfig:
            double_z: false
            z_channels: 256
            resolution: 256
            in_channels: 1
            out_ch: 3
            ch: 128
            ch_mult:
            - 1
            - 1
            - 2
            - 2
            - 4
            num_res_blocks: 2
            attn_resolutions:
            - 16
            dropout: 0.0
          lossconfig:
            target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
            params:
                disc_conditional: False
                disc_in_channels: 3
                disc_start: 30001
                disc_weight: 0.8
                codebook_weight: 1.0
    unconditional: True

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/ubuntu/shangyuc_data/datasets/ffhq-dataset-master/FFHQDownloadDir/FFHQimages1024x1024-20221027T033209Z/train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /home/ubuntu/shangyuc_data/datasets/ffhq-dataset-master/FFHQDownloadDir/FFHQimages1024x1024-20221027T033209Z/val.txt
        size: 256

